//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fogasok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fogasok()
        {
            this.Receptek = new HashSet<Receptek>();
        }
    
        public int FogasID { get; set; }
        public string FogasNev { get; set; }
        public byte[] Kep { get; set; }
        public string Leiras { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receptek> Receptek { get; set; }
    }
}
