//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MennyisegiEgysegek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MennyisegiEgysegek()
        {
            this.Nyersanyagok = new HashSet<Nyersanyagok>();
        }
    
        public int MennyisegiEgysegID { get; set; }
        public string EgysegNev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nyersanyagok> Nyersanyagok { get; set; }
    }
}
