//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EtkeztetesEntities : DbContext
    {
        public EtkeztetesEntities()
            : base("name=EtkeztetesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fogasok> Fogasok { get; set; }
        public virtual DbSet<MennyisegiEgysegek> MennyisegiEgysegek { get; set; }
        public virtual DbSet<Nyersanyagok> Nyersanyagok { get; set; }
        public virtual DbSet<Receptek> Receptek { get; set; }
    }
}
