//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptek
    {
        public int ReceptID { get; set; }
        public Nullable<int> FogasID { get; set; }
        public Nullable<int> NyersanyagID { get; set; }
        public Nullable<double> Mennyiseg_4fo { get; set; }
    
        public virtual Fogasok Fogasok { get; set; }
        public virtual Nyersanyagok Nyersanyagok { get; set; }
    }
}
